# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Oscar/Documents/GitProjects/N2End

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Oscar/Documents/GitProjects/N2End

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Oscar/Documents/GitProjects/N2End/CMakeFiles /mnt/c/Users/Oscar/Documents/GitProjects/N2End/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Oscar/Documents/GitProjects/N2End/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named N2End

# Build rule for target.
N2End: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 N2End
.PHONY : N2End

# fast build rule for target.
N2End/fast:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/build
.PHONY : N2End/fast

src/ControllerEngine.o: src/ControllerEngine.cpp.o

.PHONY : src/ControllerEngine.o

# target to build an object file
src/ControllerEngine.cpp.o:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/ControllerEngine.cpp.o
.PHONY : src/ControllerEngine.cpp.o

src/ControllerEngine.i: src/ControllerEngine.cpp.i

.PHONY : src/ControllerEngine.i

# target to preprocess a source file
src/ControllerEngine.cpp.i:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/ControllerEngine.cpp.i
.PHONY : src/ControllerEngine.cpp.i

src/ControllerEngine.s: src/ControllerEngine.cpp.s

.PHONY : src/ControllerEngine.s

# target to generate assembly for a file
src/ControllerEngine.cpp.s:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/ControllerEngine.cpp.s
.PHONY : src/ControllerEngine.cpp.s

src/View/TermWin.o: src/View/TermWin.cpp.o

.PHONY : src/View/TermWin.o

# target to build an object file
src/View/TermWin.cpp.o:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/View/TermWin.cpp.o
.PHONY : src/View/TermWin.cpp.o

src/View/TermWin.i: src/View/TermWin.cpp.i

.PHONY : src/View/TermWin.i

# target to preprocess a source file
src/View/TermWin.cpp.i:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/View/TermWin.cpp.i
.PHONY : src/View/TermWin.cpp.i

src/View/TermWin.s: src/View/TermWin.cpp.s

.PHONY : src/View/TermWin.s

# target to generate assembly for a file
src/View/TermWin.cpp.s:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/View/TermWin.cpp.s
.PHONY : src/View/TermWin.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/Contact.o: src/model/Contact.cpp.o

.PHONY : src/model/Contact.o

# target to build an object file
src/model/Contact.cpp.o:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/Contact.cpp.o
.PHONY : src/model/Contact.cpp.o

src/model/Contact.i: src/model/Contact.cpp.i

.PHONY : src/model/Contact.i

# target to preprocess a source file
src/model/Contact.cpp.i:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/Contact.cpp.i
.PHONY : src/model/Contact.cpp.i

src/model/Contact.s: src/model/Contact.cpp.s

.PHONY : src/model/Contact.s

# target to generate assembly for a file
src/model/Contact.cpp.s:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/Contact.cpp.s
.PHONY : src/model/Contact.cpp.s

src/model/Message.o: src/model/Message.cpp.o

.PHONY : src/model/Message.o

# target to build an object file
src/model/Message.cpp.o:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/Message.cpp.o
.PHONY : src/model/Message.cpp.o

src/model/Message.i: src/model/Message.cpp.i

.PHONY : src/model/Message.i

# target to preprocess a source file
src/model/Message.cpp.i:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/Message.cpp.i
.PHONY : src/model/Message.cpp.i

src/model/Message.s: src/model/Message.cpp.s

.PHONY : src/model/Message.s

# target to generate assembly for a file
src/model/Message.cpp.s:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/Message.cpp.s
.PHONY : src/model/Message.cpp.s

src/model/ModelEngine.o: src/model/ModelEngine.cpp.o

.PHONY : src/model/ModelEngine.o

# target to build an object file
src/model/ModelEngine.cpp.o:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/ModelEngine.cpp.o
.PHONY : src/model/ModelEngine.cpp.o

src/model/ModelEngine.i: src/model/ModelEngine.cpp.i

.PHONY : src/model/ModelEngine.i

# target to preprocess a source file
src/model/ModelEngine.cpp.i:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/ModelEngine.cpp.i
.PHONY : src/model/ModelEngine.cpp.i

src/model/ModelEngine.s: src/model/ModelEngine.cpp.s

.PHONY : src/model/ModelEngine.s

# target to generate assembly for a file
src/model/ModelEngine.cpp.s:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/ModelEngine.cpp.s
.PHONY : src/model/ModelEngine.cpp.s

src/model/fileParse.o: src/model/fileParse.cpp.o

.PHONY : src/model/fileParse.o

# target to build an object file
src/model/fileParse.cpp.o:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/fileParse.cpp.o
.PHONY : src/model/fileParse.cpp.o

src/model/fileParse.i: src/model/fileParse.cpp.i

.PHONY : src/model/fileParse.i

# target to preprocess a source file
src/model/fileParse.cpp.i:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/fileParse.cpp.i
.PHONY : src/model/fileParse.cpp.i

src/model/fileParse.s: src/model/fileParse.cpp.s

.PHONY : src/model/fileParse.s

# target to generate assembly for a file
src/model/fileParse.cpp.s:
	$(MAKE) -f CMakeFiles/N2End.dir/build.make CMakeFiles/N2End.dir/src/model/fileParse.cpp.s
.PHONY : src/model/fileParse.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... N2End"
	@echo "... src/ControllerEngine.o"
	@echo "... src/ControllerEngine.i"
	@echo "... src/ControllerEngine.s"
	@echo "... src/View/TermWin.o"
	@echo "... src/View/TermWin.i"
	@echo "... src/View/TermWin.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/Contact.o"
	@echo "... src/model/Contact.i"
	@echo "... src/model/Contact.s"
	@echo "... src/model/Message.o"
	@echo "... src/model/Message.i"
	@echo "... src/model/Message.s"
	@echo "... src/model/ModelEngine.o"
	@echo "... src/model/ModelEngine.i"
	@echo "... src/model/ModelEngine.s"
	@echo "... src/model/fileParse.o"
	@echo "... src/model/fileParse.i"
	@echo "... src/model/fileParse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

